version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smarttrack-mysql
    environment:
      MYSQL_DATABASE: smarttrack_inventory
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: smarttrack-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smarttrack_inventory?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      APP_CORS_ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: smarttrack-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
